### PR TITLE
docs: samples for managing reservations

### LINKED ISSUE #56: Provide sample codes on how to use methods
I'm reading through the documentation and it's very hard to navigate. There are no indications on how to use the classes.

For example, in `update_reservation`, what is the `update_mask`? Why is it needed? Why is there a `request` field? What is the difference between that and `Reservation`?

### PR DESCRIPTION
**Pull request by tswast**
TODO: Testing these samples requires a capacity commitment. I created on manually on my dev project, but I think we'll want to programmatically create one in our CI project(s).

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-reservation/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #56  🦕

### CODE REVIEW

**Comment by tswast** [comment]
```
args = (parent: "projects/python-docs-samples-tests/locations/US"
capacity_commitment {
  slot_count: 100
  plan: FLEX
}
,)
kwargs = {'metadata': [('x-goog-request-params', 'parent=projects/python-docs-samples-tests/locations/US'), ('x-goog-api-client', 'gl-python/3.6.13 grpc/1.39.0 gax/1.31.1 gapic/1.2.2')]}

    @six.wraps(callable_)
    def error_remapped_callable(*args, **kwargs):
        try:
            return callable_(*args, **kwargs)
        except grpc.RpcError as exc:
>           six.raise_from(exceptions.from_grpc_error(exc), exc)
E           google.api_core.exceptions.FailedPrecondition: 400 Google owned projects are not allowed to buy FLEX slots, please see go/bq-flex-restrictions for details.

.nox/py-3-6/lib/python3.6/site-packages/google/api_core/grpc_helpers.py:69: FailedPrecondition
- generated xml file: /tmpfs/src/github/python-bigquery-reservation/samples/snippets/sponge_log.xml -
```


I've requested FLEX slot usage in internal bug 196099709

**Comment by tswast** [comment]
It worked! We can now use FLEX commitments on the samples project.

**Review by shollyman — APPROVED** [review]

**Comment by jamiet-msm** [comment]
@tswast  Hugely appreciate you providing these samples, saved me a big job. I was specifically looking for an example for `update_reservation`, the field_mask stuff was non-obvious to me.

**Comment by tswast** [comment]
> @tswast Hugely appreciate you providing these samples, saved me a big job. I was specifically looking for an example for `update_reservation`, the field_mask stuff was non-obvious to me.

@jamiet-msm I'm so glad that you found them helpful. Thanks for the feedback.

**Pull request merged**
